=== dubdeeber/webtech/dubdeeber/cars/car-schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT cars (car)*>
<!ELEMENT car (licensePlateNumber,brand,model,color,engine,year,price,owner?)>
<!ELEMENT licensePlateNumber (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT engine (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT owner (name,phoneNumber+,email)>
<!ELEMENT name (firstName,lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST engine motorType CDATA #REQUIRED>
<!ATTLIST engine hp CDATA #REQUIRED>
<!ATTLIST price currency CDATA #REQUIRED>
<!ATTLIST phoneNumber type (phone| fax) #REQUIRED> 
<!ATTLIST enprice currency CDATA #REQUIRED>

=== dubdeeber/webtech/dubdeeber/cars/cars.xml
<?xml version="1.0"?>
<!DOCTYPE cars SYSTEM "./car-schema.dtd">
<?xml-stylesheet type="text/css" href="car-styles.css"?>
<cars>
    <car>
        <licensePlateNumber>AABB12</licensePlateNumber>
        <brand>Volkswagen</brand>
        <model>Golf 7 GTI</model>
        <color>black</color>
        <engine motorType="2.0 TSI" hp="220"/>
        <year>2015</year>
        <price currency="HUF">7.000.000</price>
        <owner>
            <name>
                <firstName>John</firstName>
                <lastName>Doe</lastName>
            </name>
            <phoneNumber type="phone">123456789</phoneNumber>
            <phoneNumber type="fax">001234567</phoneNumber>
            <email>john.doe@gmail.com</email>
        </owner>
    </car>
    <car>
        <licensePlateNumber>AABB13</licensePlateNumber>
        <brand>Porsche</brand>
        <model>911 GT3 RS</model>
        <color>green</color>
        <engine motorType="4.0" hp="525"/>
        <year>2022</year>
        <price currency="EUR">170.000</price>
    </car>
    <car>
        <licensePlateNumber>AABB14</licensePlateNumber>
        <brand>Audi</brand>
        <model>RS Sportback</model>
        <color>graphite</color>
        <engine motorType="4.0" hp="621"/>
        <year>2020</year>
        <price currency="USD">120.000</price>
    </car>
</cars>
